# Numpy Tutorial
#  
## Numpy의 기본, 다차원 배열(n-dimensional arrays)


Numpy는 선형대수 계산을 지원하는 패키지로 numpy패키지를 사용하기 위해선 선형대수학에 대한 이해가 선행되어야 한다.

Numpy 패키지를 이해하기 위해 가장 기초적인 배열 적용부터 살펴보자.


In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
type(a)

numpy.ndarray

In [8]:
a.itemsize

4

In [9]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

In [11]:
#array 생성
a = np.array([2,3,4]) #array를 만들기 위해서는 리스트나 튜플 형식으로 입력해주어야 한다.
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [18]:
b = np.array([1.1, 2.3, 3.5], dtype = 'i')
b

array([1, 2, 3], dtype=int32)

In [14]:
#영행렬 만들기

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#1로만 구성된 행렬 만들기

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
#.empty()

np.empty((6,5))

array([[9.92896192e-312, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 4.22790516e-307],
       [5.02034658e+175, 4.99705907e+174, 2.57543256e-056,
        5.64487515e-038, 5.74000513e+174],
       [1.47763641e+248, 1.16096346e-028, 7.69165785e+218,
        1.35617292e+248, 1.65241855e-076],
       [2.09163980e-076, 8.39531908e+165, 1.36368047e+161,
        4.30423406e-096, 6.32299154e+233],
       [6.48224638e+170, 5.22411352e+257, 5.74020278e+180,
        8.37174974e-144, 1.41529402e+161],
       [6.00736899e-067, 3.46027951e+097, 1.48778639e-076,
        2.91011350e+126, 2.59297589e-306]])

In [35]:
#.identity()

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#np.aragnge()

np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
#.reshape

np.arange(12).reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [40]:
#다차원 reshape

m = np.arange(36).reshape(2,3,6)
m

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [41]:
m.ndim

3

In [42]:
mm = np.arange(36).reshape(2,2,3,3)
mm

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [43]:
mm.ndim

4