# Numpy Tutorial
# 
## Numpy Array의 자료형 알아보기

In [3]:
#Numpy Array 자료형 지정
import numpy as np

a = np.array([11,24,35], dtype = np.int8)
a.dtype

dtype('int8')

In [7]:
#만약 해당 비트 안에 포함되지 않는 숫자를 지정할 경우
#320은 -127~128 안에 속하지 않으므로 int8이 표현할 수 없음
b = np.array([129,11,23], dtype = np.int8)
b

array([-127,   11,   23], dtype=int8)

In [10]:
#Numpy 자료형 지정 using code

a = np.array([1.1, 3.2, 5.3], dtype = 'f2')
a.dtype

dtype('float16')

In [11]:
#array 함수 안 쓰고 np.자료형([list])로 바로 array에 형식까지 지정하기

b = np.float16([1.1, 2.2, 3.3])
b.dtype

dtype('float16')

In [12]:
type(b)

numpy.ndarray

In [13]:
b

array([1.1, 2.2, 3.3], dtype=float16)

In [15]:
#자료형 변환 .astype(np.자료형)
c = b.astype(np.int8)
c

array([1, 2, 3], dtype=int8)

In [27]:
#int와 int64 비교
#int
x = 1
x_d = pd.DataFrame(dir(x))
x_d.shape

(71, 1)

In [26]:
#int와 int64비교
#int64
x_64 = np.int64(1)
x_64_d = pd.DataFrame(dir(x_64))
x_64_d.shape

(136, 1)